name: Deodand
favicon: null
layout_spectrum: 0.39861603593453765
typography_spectrum: 0.7484354602638632
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.14228701288811862
  lightness: 0.9622913603670895
  saturation: 0.7871084164362401
  rhythmicContrast: 0.8390808291733265
purpose: []
