name: Deodand
favicon: null
layout_spectrum: 0.49777
typography_spectrum: 0.7484354602638632
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.0625
  lightness: 0.625
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
